<template>
        <v-dialog
          v-model="show"
          transition="dialog-top-transition"
          max-width="600"
        >       
            <v-card
            rounded="t-xl"
            >
              <v-toolbar
              :color="!!color?color:'white'"
              >              
                    <v-btn
                    icon      
                    color="grey darken-1"              
                    @click="close"
                    >
                    <v-icon>mdi-close</v-icon>
                    </v-btn>
                    <v-spacer/>
                    <v-btn
                    v-if="showAddBtn"
                    class="rounded-pill"
                    color="primary"
                    @click="add"
                    >Add
                    </v-btn>
                    <v-btn
                    v-if="showEditBtn"
                    color="primary"
                    fab
                    small
                    dark
                    @click="edit"
                    >
                       <v-icon>
                         mdi-pencil
                       </v-icon>
                    </v-btn>
                    <v-btn
                    v-else
                    class="rounded-pill"
                    color="primary"
                    @click="update"
                    >save</v-btn>
              </v-toolbar>
              <v-card-text>
                 <EventForm/>
              </v-card-text>
            </v-card>        
        </v-dialog>
</template>
<script>
import EventForm from './EventForm.vue'
import {mapState} from 'vuex'

export default {
    components:{
      EventForm
    },
    computed:{
        ...mapState({
            show : state => state.calendar.showDialog,
            color: state =>state.calendar.event.color,
            showAddBtn:state=>state.calendar.showAddBtn,
            showEditBtn:state=>state.calendar.showEditBtn,
        })
    },
    methods:{
        close(){
            this.$store.dispatch('calendar/cleanEventModalForm');
            this.$store.dispatch('calendar/closeEventModalForm');
        },
        add(){
          this.$store.dispatch('calendar/addEvent');
        },
        edit(){
          this.$store.dispatch('calendar/enableForm');
        },
        update(){
          this.$store.dispatch('calendar/updateEvent');
        }
    }
}
</script>